
#Archivo para crear un contenedor de MySQL a traves de Docker Compose
#SE define variables como el nombre del contenedor, la imagen a utilizar, las variables de entorno y los puertos a exponer
#El volumen se utiliza para persistir los datos de la base de datos

version: "3.9"
services:
  db:
    image: mysql:latest
    conainer_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: waterapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: